### ISSUE TITLE
kubeconfig pulumi error

### ISSUE THREAD

**Issue by braaar** [ayrorg/infra#80]
We are getting a [strange error from pulumi preview action](https://github.com/ayrorg/infra/actions/runs/6158524628/job/16711484632?pr=79)
```
    pulumi:pulumi:Stack (infra-core-prod):
      error: Error: call of google-native:container/v1:Cluster/getKubeconfig returned an error: marshaling properties: awaiting input property "kubeconfig": no output "endpoint" on resource ""
          at Object.callback (/home/runner/work/infra/infra/node_modules/@pulumi/google-native/node_modules/@pulumi/runtime/invoke.ts:282:37)
          at Object.onReceiveStatus (/home/runner/work/infra/infra/node_modules/@grpc/grpc-js/src/client.ts:338:26)
          at Object.onReceiveStatus (/home/runner/work/infra/infra/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
          at Object.onReceiveStatus (/home/runner/work/infra/infra/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
          at /home/runner/work/infra/infra/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
          at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by braaar** [comment]
Here's the related code:
```ts
import * as k8s from '@pulumi/kubernetes';
import { cluster } from '../google/gke';

export const provider = new k8s.Provider('k8s-provider', {
  kubeconfig: cluster.getKubeconfig(),
});
```

**Comment by braaar** [comment]
and in `google/gke`:
```ts
import * as google from '@pulumi/google-native';
import { region, zone } from '../config';
import { provider } from './providers';

const serverConfig = google.container.v1.getServerConfigOutput({
  location: region,
});

const engineVersion = serverConfig.apply((conf) => conf.validMasterVersions[0]);

export const cluster = new google.container.v1.Cluster(
  'main-cluster',
  {
    name: 'ayr-main-cluster',
    initialClusterVersion: engineVersion,
    autopilot: { enabled: true },
  },
  { provider: provider.google },
);
```

**Comment by braaar** [comment]
[The issue still presists](https://github.com/ayrorg/infra/actions/runs/6159005573/job/16712939524?pr=79)

**Comment by maulerjan** [comment]
+1, I have to `pulumi down` & `pulumi up` the whole stack whenever I make changes to the cluster. I'm not running on production yet, so it's not an issue right now, but it will be.
